//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrausRGA.GetRMAServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UpdatedbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UserJoiningDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDateTime {
            get {
                return this.UpdatedDateTimeField;
            }
            set {
                if ((this.UpdatedDateTimeField.Equals(value) != true)) {
                    this.UpdatedDateTimeField = value;
                    this.RaisePropertyChanged("UpdatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Updatedby {
            get {
                return this.UpdatedbyField;
            }
            set {
                if ((this.UpdatedbyField.Equals(value) != true)) {
                    this.UpdatedbyField = value;
                    this.RaisePropertyChanged("Updatedby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAddress {
            get {
                return this.UserAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAddressField, value) != true)) {
                    this.UserAddressField = value;
                    this.RaisePropertyChanged("UserAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFullName {
            get {
                return this.UserFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFullNameField, value) != true)) {
                    this.UserFullNameField = value;
                    this.RaisePropertyChanged("UserFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UserJoiningDate {
            get {
                return this.UserJoiningDateField;
            }
            set {
                if ((this.UserJoiningDateField.Equals(value) != true)) {
                    this.UserJoiningDateField = value;
                    this.RaisePropertyChanged("UserJoiningDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class ReturnDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatesDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerName1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerName2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> DecisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DeliveryDatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PONumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RMANumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> RMAStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReturnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReturnIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipmentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendoeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address3 {
            get {
                return this.Address3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address3Field, value) != true)) {
                    this.Address3Field = value;
                    this.RaisePropertyChanged("Address3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatesDate {
            get {
                return this.CreatesDateField;
            }
            set {
                if ((this.CreatesDateField.Equals(value) != true)) {
                    this.CreatesDateField = value;
                    this.RaisePropertyChanged("CreatesDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName1 {
            get {
                return this.CustomerName1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerName1Field, value) != true)) {
                    this.CustomerName1Field = value;
                    this.RaisePropertyChanged("CustomerName1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName2 {
            get {
                return this.CustomerName2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerName2Field, value) != true)) {
                    this.CustomerName2Field = value;
                    this.RaisePropertyChanged("CustomerName2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> Decision {
            get {
                return this.DecisionField;
            }
            set {
                if ((this.DecisionField.Equals(value) != true)) {
                    this.DecisionField = value;
                    this.RaisePropertyChanged("Decision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DeliveryDat {
            get {
                return this.DeliveryDatField;
            }
            set {
                if ((this.DeliveryDatField.Equals(value) != true)) {
                    this.DeliveryDatField = value;
                    this.RaisePropertyChanged("DeliveryDat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PONumber {
            get {
                return this.PONumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PONumberField, value) != true)) {
                    this.PONumberField = value;
                    this.RaisePropertyChanged("PONumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RMANumber {
            get {
                return this.RMANumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RMANumberField, value) != true)) {
                    this.RMANumberField = value;
                    this.RaisePropertyChanged("RMANumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> RMAStatus {
            get {
                return this.RMAStatusField;
            }
            set {
                if ((this.RMAStatusField.Equals(value) != true)) {
                    this.RMAStatusField = value;
                    this.RaisePropertyChanged("RMAStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReturnID {
            get {
                return this.ReturnIDField;
            }
            set {
                if ((this.ReturnIDField.Equals(value) != true)) {
                    this.ReturnIDField = value;
                    this.RaisePropertyChanged("ReturnID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnReason {
            get {
                return this.ReturnReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnReasonField, value) != true)) {
                    this.ReturnReasonField = value;
                    this.RaisePropertyChanged("ReturnReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipmentNumber {
            get {
                return this.ShipmentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipmentNumberField, value) != true)) {
                    this.ShipmentNumberField = value;
                    this.RaisePropertyChanged("ShipmentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((this.UpdatedByField.Equals(value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDate {
            get {
                return this.UpdatedDateField;
            }
            set {
                if ((this.UpdatedDateField.Equals(value) != true)) {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendoeName {
            get {
                return this.VendoeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VendoeNameField, value) != true)) {
                    this.VendoeNameField = value;
                    this.RaisePropertyChanged("VendoeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorNumber {
            get {
                return this.VendorNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorNumberField, value) != true)) {
                    this.VendorNumberField = value;
                    this.RaisePropertyChanged("VendorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReasonsDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class ReasonsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReasonIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReasonID {
            get {
                return this.ReasonIDField;
            }
            set {
                if ((this.ReasonIDField.Equals(value) != true)) {
                    this.ReasonIDField = value;
                    this.RaisePropertyChanged("ReasonID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuditDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class AuditDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ActionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserLogIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ActionTime {
            get {
                return this.ActionTimeField;
            }
            set {
                if ((this.ActionTimeField.Equals(value) != true)) {
                    this.ActionTimeField = value;
                    this.RaisePropertyChanged("ActionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionType {
            get {
                return this.ActionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionTypeField, value) != true)) {
                    this.ActionTypeField = value;
                    this.RaisePropertyChanged("ActionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionValue {
            get {
                return this.ActionValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionValueField, value) != true)) {
                    this.ActionValueField = value;
                    this.RaisePropertyChanged("ActionValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserLogID {
            get {
                return this.UserLogIDField;
            }
            set {
                if ((this.UserLogIDField.Equals(value) != true)) {
                    this.UserLogIDField = value;
                    this.RaisePropertyChanged("UserLogID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RMAInfoDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class RMAInfoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerName1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerName2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeliveredQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DeliveryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpectedQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PONumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RMANumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReturnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReturnedQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipmentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCLCOD_0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address3 {
            get {
                return this.Address3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address3Field, value) != true)) {
                    this.Address3Field = value;
                    this.RaisePropertyChanged("Address3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName1 {
            get {
                return this.CustomerName1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerName1Field, value) != true)) {
                    this.CustomerName1Field = value;
                    this.RaisePropertyChanged("CustomerName1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName2 {
            get {
                return this.CustomerName2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerName2Field, value) != true)) {
                    this.CustomerName2Field = value;
                    this.RaisePropertyChanged("CustomerName2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeliveredQty {
            get {
                return this.DeliveredQtyField;
            }
            set {
                if ((this.DeliveredQtyField.Equals(value) != true)) {
                    this.DeliveredQtyField = value;
                    this.RaisePropertyChanged("DeliveredQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DeliveryDate {
            get {
                return this.DeliveryDateField;
            }
            set {
                if ((this.DeliveryDateField.Equals(value) != true)) {
                    this.DeliveryDateField = value;
                    this.RaisePropertyChanged("DeliveryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpectedQty {
            get {
                return this.ExpectedQtyField;
            }
            set {
                if ((this.ExpectedQtyField.Equals(value) != true)) {
                    this.ExpectedQtyField = value;
                    this.RaisePropertyChanged("ExpectedQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PONumber {
            get {
                return this.PONumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PONumberField, value) != true)) {
                    this.PONumberField = value;
                    this.RaisePropertyChanged("PONumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RMANumber {
            get {
                return this.RMANumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RMANumberField, value) != true)) {
                    this.RMANumberField = value;
                    this.RaisePropertyChanged("RMANumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReturnDate {
            get {
                return this.ReturnDateField;
            }
            set {
                if ((this.ReturnDateField.Equals(value) != true)) {
                    this.ReturnDateField = value;
                    this.RaisePropertyChanged("ReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnedQty {
            get {
                return this.ReturnedQtyField;
            }
            set {
                if ((this.ReturnedQtyField.Equals(value) != true)) {
                    this.ReturnedQtyField = value;
                    this.RaisePropertyChanged("ReturnedQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKUNumber {
            get {
                return this.SKUNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUNumberField, value) != true)) {
                    this.SKUNumberField = value;
                    this.RaisePropertyChanged("SKUNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipmentNumber {
            get {
                return this.ShipmentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipmentNumberField, value) != true)) {
                    this.ShipmentNumberField = value;
                    this.RaisePropertyChanged("ShipmentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCLCOD_0 {
            get {
                return this.TCLCOD_0Field;
            }
            set {
                if ((object.ReferenceEquals(this.TCLCOD_0Field, value) != true)) {
                    this.TCLCOD_0Field = value;
                    this.RaisePropertyChanged("TCLCOD_0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorName {
            get {
                return this.VendorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorNameField, value) != true)) {
                    this.VendorNameField = value;
                    this.RaisePropertyChanged("VendorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorNumber {
            get {
                return this.VendorNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorNumberField, value) != true)) {
                    this.VendorNumberField = value;
                    this.RaisePropertyChanged("VendorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleDTO", Namespace="http://schemas.datacontract.org/2004/07/KrausWarehouseServices.DTO.RMA")]
    [System.SerializableAttribute()]
    public partial class RoleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UpdatedbyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedDateTime {
            get {
                return this.UpdatedDateTimeField;
            }
            set {
                if ((this.UpdatedDateTimeField.Equals(value) != true)) {
                    this.UpdatedDateTimeField = value;
                    this.RaisePropertyChanged("UpdatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Updatedby {
            get {
                return this.UpdatedbyField;
            }
            set {
                if ((this.UpdatedbyField.Equals(value) != true)) {
                    this.UpdatedbyField = value;
                    this.RaisePropertyChanged("Updatedby");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetRMAServiceRef.IGet")]
    public interface IGet {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/xGet", ReplyAction="http://tempuri.org/IGet/xGetResponse")]
        KrausRGA.GetRMAServiceRef.UserDTO[] xGet(string EnumGetTypeString, string Parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/UserAll", ReplyAction="http://tempuri.org/IGet/UserAllResponse")]
        KrausRGA.GetRMAServiceRef.UserDTO[] UserAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/UserByUserID", ReplyAction="http://tempuri.org/IGet/UserByUserIDResponse")]
        KrausRGA.GetRMAServiceRef.UserDTO UserByUserID(System.Guid UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/UserByRoleID", ReplyAction="http://tempuri.org/IGet/UserByRoleIDResponse")]
        KrausRGA.GetRMAServiceRef.UserDTO[] UserByRoleID(System.Guid RoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/UserByUserName", ReplyAction="http://tempuri.org/IGet/UserByUserNameResponse")]
        KrausRGA.GetRMAServiceRef.UserDTO UserByUserName(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/ReturnAll", ReplyAction="http://tempuri.org/IGet/ReturnAllResponse")]
        KrausRGA.GetRMAServiceRef.ReturnDTO[] ReturnAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/ReturnByReturnID", ReplyAction="http://tempuri.org/IGet/ReturnByReturnIDResponse")]
        KrausRGA.GetRMAServiceRef.ReturnDTO ReturnByReturnID(System.Guid ReturnID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/ReturnByReturnDetailID", ReplyAction="http://tempuri.org/IGet/ReturnByReturnDetailIDResponse")]
        KrausRGA.GetRMAServiceRef.ReturnDTO[] ReturnByReturnDetailID(System.Guid ReturnDetailsID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/ReturnByRMANumber", ReplyAction="http://tempuri.org/IGet/ReturnByRMANumberResponse")]
        KrausRGA.GetRMAServiceRef.ReturnDTO ReturnByRMANumber(string RMANumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/ReasonsAll", ReplyAction="http://tempuri.org/IGet/ReasonsAllResponse")]
        KrausRGA.GetRMAServiceRef.ReasonsDTO[] ReasonsAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/ReasonByCategoryName", ReplyAction="http://tempuri.org/IGet/ReasonByCategoryNameResponse")]
        KrausRGA.GetRMAServiceRef.ReasonsDTO[] ReasonByCategoryName(string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/AuditAll", ReplyAction="http://tempuri.org/IGet/AuditAllResponse")]
        KrausRGA.GetRMAServiceRef.AuditDTO[] AuditAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/RMAInfoByShippingNumber", ReplyAction="http://tempuri.org/IGet/RMAInfoByShippingNumberResponse")]
        KrausRGA.GetRMAServiceRef.RMAInfoDTO[] RMAInfoByShippingNumber(string ShippingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/RMAInfoBySONumber", ReplyAction="http://tempuri.org/IGet/RMAInfoBySONumberResponse")]
        KrausRGA.GetRMAServiceRef.RMAInfoDTO[] RMAInfoBySONumber(string SONumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/RMAInfoByPONumber", ReplyAction="http://tempuri.org/IGet/RMAInfoByPONumberResponse")]
        KrausRGA.GetRMAServiceRef.RMAInfoDTO[] RMAInfoByPONumber(string PONumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/RMAInfoBySRNumber", ReplyAction="http://tempuri.org/IGet/RMAInfoBySRNumberResponse")]
        KrausRGA.GetRMAServiceRef.RMAInfoDTO[] RMAInfoBySRNumber(string SRNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/RoleAll", ReplyAction="http://tempuri.org/IGet/RoleAllResponse")]
        KrausRGA.GetRMAServiceRef.RoleDTO[] RoleAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGet/RoleByRoleID", ReplyAction="http://tempuri.org/IGet/RoleByRoleIDResponse")]
        KrausRGA.GetRMAServiceRef.RoleDTO RoleByRoleID(System.Guid RoleID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetChannel : KrausRGA.GetRMAServiceRef.IGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetClient : System.ServiceModel.ClientBase<KrausRGA.GetRMAServiceRef.IGet>, KrausRGA.GetRMAServiceRef.IGet {
        
        public GetClient() {
         
        }
        
        public GetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KrausRGA.GetRMAServiceRef.UserDTO[] xGet(string EnumGetTypeString, string Parameters) {
            return base.Channel.xGet(EnumGetTypeString, Parameters);
        }
        
        public KrausRGA.GetRMAServiceRef.UserDTO[] UserAll() {
            return base.Channel.UserAll();
        }
        
        public KrausRGA.GetRMAServiceRef.UserDTO UserByUserID(System.Guid UserID) {
            return base.Channel.UserByUserID(UserID);
        }
        
        public KrausRGA.GetRMAServiceRef.UserDTO[] UserByRoleID(System.Guid RoleID) {
            return base.Channel.UserByRoleID(RoleID);
        }
        
        public KrausRGA.GetRMAServiceRef.UserDTO UserByUserName(string UserName) {
            return base.Channel.UserByUserName(UserName);
        }
        
        public KrausRGA.GetRMAServiceRef.ReturnDTO[] ReturnAll() {
            return base.Channel.ReturnAll();
        }
        
        public KrausRGA.GetRMAServiceRef.ReturnDTO ReturnByReturnID(System.Guid ReturnID) {
            return base.Channel.ReturnByReturnID(ReturnID);
        }
        
        public KrausRGA.GetRMAServiceRef.ReturnDTO[] ReturnByReturnDetailID(System.Guid ReturnDetailsID) {
            return base.Channel.ReturnByReturnDetailID(ReturnDetailsID);
        }
        
        public KrausRGA.GetRMAServiceRef.ReturnDTO ReturnByRMANumber(string RMANumber) {
            return base.Channel.ReturnByRMANumber(RMANumber);
        }
        
        public KrausRGA.GetRMAServiceRef.ReasonsDTO[] ReasonsAll() {
            return base.Channel.ReasonsAll();
        }
        
        public KrausRGA.GetRMAServiceRef.ReasonsDTO[] ReasonByCategoryName(string CategoryName) {
            return base.Channel.ReasonByCategoryName(CategoryName);
        }
        
        public KrausRGA.GetRMAServiceRef.AuditDTO[] AuditAll() {
            return base.Channel.AuditAll();
        }
        
        public KrausRGA.GetRMAServiceRef.RMAInfoDTO[] RMAInfoByShippingNumber(string ShippingNumber) {
            return base.Channel.RMAInfoByShippingNumber(ShippingNumber);
        }
        
        public KrausRGA.GetRMAServiceRef.RMAInfoDTO[] RMAInfoBySONumber(string SONumber) {
            return base.Channel.RMAInfoBySONumber(SONumber);
        }
        
        public KrausRGA.GetRMAServiceRef.RMAInfoDTO[] RMAInfoByPONumber(string PONumber) {
            return base.Channel.RMAInfoByPONumber(PONumber);
        }
        
        public KrausRGA.GetRMAServiceRef.RMAInfoDTO[] RMAInfoBySRNumber(string SRNumber) {
            return base.Channel.RMAInfoBySRNumber(SRNumber);
        }
        
        public KrausRGA.GetRMAServiceRef.RoleDTO[] RoleAll() {
            return base.Channel.RoleAll();
        }
        
        public KrausRGA.GetRMAServiceRef.RoleDTO RoleByRoleID(System.Guid RoleID) {
            return base.Channel.RoleByRoleID(RoleID);
        }
    }
}
