//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrausRGA.DeleteRMAServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeleteRMAServiceRef.IDelete")]
    public interface IDelete {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDelete/ReturnDetailsallForeignKeyTables", ReplyAction="http://tempuri.org/IDelete/ReturnDetailsallForeignKeyTablesResponse")]
        bool ReturnDetailsallForeignKeyTables(System.Guid ReturnDetailID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeleteChannel : KrausRGA.DeleteRMAServiceRef.IDelete, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteClient : System.ServiceModel.ClientBase<KrausRGA.DeleteRMAServiceRef.IDelete>, KrausRGA.DeleteRMAServiceRef.IDelete {
        
        public DeleteClient() {
        }
        
        public DeleteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeleteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ReturnDetailsallForeignKeyTables(System.Guid ReturnDetailID) {
            return base.Channel.ReturnDetailsallForeignKeyTables(ReturnDetailID);
        }
    }
}
